// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtiE2Z0S6LF63ANsRzq8QaItdUnF_Km0U',
    appId: '1:33185282249:web:c72e774e1e9cd2b8557518',
    messagingSenderId: '33185282249',
    projectId: 'future-it-c63d3',
    authDomain: 'future-it-c63d3.firebaseapp.com',
    storageBucket: 'future-it-c63d3.appspot.com',
    measurementId: 'G-GFPXMGB18S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3USBmDUVaJwZsICtiOgq75qmgSsK2UJQ',
    appId: '1:33185282249:android:b8ab779d64301338557518',
    messagingSenderId: '33185282249',
    projectId: 'future-it-c63d3',
    storageBucket: 'future-it-c63d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9hd5GsfV-qB2L2sAufxYIWqmOp4qXJiA',
    appId: '1:33185282249:ios:7acddda20e70985c557518',
    messagingSenderId: '33185282249',
    projectId: 'future-it-c63d3',
    storageBucket: 'future-it-c63d3.appspot.com',
    androidClientId: '33185282249-4c27c4uek28m72d2odejegck27uqilcm.apps.googleusercontent.com',
    iosClientId: '33185282249-cbt4evu1tk2vk04djhabpjhidt25vp5d.apps.googleusercontent.com',
    iosBundleId: 'com.example.futureit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9hd5GsfV-qB2L2sAufxYIWqmOp4qXJiA',
    appId: '1:33185282249:ios:c51b17f4f282a84a557518',
    messagingSenderId: '33185282249',
    projectId: 'future-it-c63d3',
    storageBucket: 'future-it-c63d3.appspot.com',
    androidClientId: '33185282249-4c27c4uek28m72d2odejegck27uqilcm.apps.googleusercontent.com',
    iosClientId: '33185282249-qmb4liu6l1ip65mf4kim1obumm45dge4.apps.googleusercontent.com',
    iosBundleId: 'com.example.futureit.RunnerTests',
  );
}
